In [1]:
#numpy, pandas, matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#1. numpy - np.ndarray(n차원 array객체)
#2. scipy - 과학, 통계 연산을 위한 파이썬. 선형 회귀, p-value, r
#3. pandas - 엑셀파일, 시계열데이터, pd.Series, pd.DataFrame
#4. matplotlib

In [3]:
#1. list - 1차원 행렬 혹은 벡터
[1,2,3,4]

[1, 2, 3, 4]

In [7]:
#array - 메모리효율적으로 
from array import array

In [9]:
array("i",[1,2,3]) # i = "signed integer"

array('i', [1, 2, 3])

In [13]:
data=np.array([1,2,3,4])

In [14]:
type(data)

numpy.ndarray

In [15]:
data[0]

1

In [17]:
data[-1]

4

In [18]:
data.sum()

10

In [19]:
data.max()

4

In [20]:
np.mean(data)

2.5

In [22]:
data.mean()

2.5

In [23]:
data1 = [
    [1,2,],
    [3,4,],
    
]

In [25]:
data1[1]

[3, 4]

In [27]:
data1[0]

[1, 2]

In [31]:
[row for row in data1]

[[1, 2], [3, 4]]

In [32]:
[row[0] for row in data1]

[1, 3]

In [33]:
data2 = np.array(data1)

In [34]:
data2

array([[1, 2],
       [3, 4]])

In [35]:
data2[0]

array([1, 2])

In [36]:
data2[1]

array([3, 4])

In [37]:
data2[0,0]

1

In [38]:
data2[0:2,0]

array([1, 3])

In [39]:
data2[:,0]

array([1, 3])

In [40]:
data2.sum(axis = 0)

array([4, 6])

In [41]:
data2.sum(axis = 1)

array([3, 7])

In [42]:
data1 = np.array([1,2,3])
data2 = np.array([2,3,4])

In [43]:
data1+data2

array([3, 5, 7])

In [44]:
[x ** 2 for x in data1]

[1, 4, 9]

In [45]:
data1 * data1

array([1, 4, 9])

In [46]:
data1 ** 2

array([1, 4, 9])

In [48]:
array1 = np.array([[1,2,],[3,4,]])

In [49]:
array2 = np.array([[1,0,],[0,1,]])

In [50]:
array1

array([[1, 2],
       [3, 4]])

In [51]:
array2

array([[1, 0],
       [0, 1]])

In [52]:
array1 * array2

array([[1, 0],
       [0, 4]])

In [53]:
np.dot(array1,array2)

array([[1, 2],
       [3, 4]])

In [54]:
array1 * np.array([[2,2,],[2,2]])

array([[2, 4],
       [6, 8]])

In [55]:
array1 * 2 #55번코드가 54번처럼 변경되어서 작동되는 것

array([[2, 4],
       [6, 8]])

In [56]:
array1.shape

(2, 2)

In [57]:
array1.ndim

2

In [58]:
len(array1.shape) == array1.ndim

True

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [61]:
np.ones(10)


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [63]:
np.arange(25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
np.arange(30).reshape((10,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])