In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import Perceptron

In [11]:
X = []
y = []
for i in range(2):
    for j in range(2):
        X.append([i,j])
        y.append(i^j)


In [12]:
for x in X:
    x.extend([x[0]*x[0],x[1]*x[1],x[0]*x[1]])

In [13]:
X = np.array(X)
y = np.array(y)

In [14]:
print(X)

[[0 0 0 0 0]
 [0 1 0 1 0]
 [1 0 1 0 0]
 [1 1 1 1 1]]


In [10]:
print(y)

[0 1 1 0]


In [15]:
x[0]

1

In [16]:
x[1]

1

In [ ]:
clf = Perceptron(n_iter = 10, shuffle = False).fit(X,y)